### ISSUE TITLE
Failing review

### ISSUE THREAD

**Issue by evandandrea** [snapcrafters/paraview#1]
Failing review:

>desktop interfaces (unity7,x11) specified without a corresponding meta/gui/*.desktop file. If using snapcraft, please see https://snapcraft.io/docs/build-snaps/metadata#fixed-assets. Otherwise, please provide a desktop file in meta/gui/*.desktop (it should reference one of the 'apps' from your snapcraft/snap.yaml). lint-snap-v2_meta_gui_desktop

**Comment by evandandrea** [comment]
@joedborg can you have a look at this?

**Comment by joedborg** [comment]
Yep @evandandrea
